# Uncomment the next line to define a global platform for your project
# platform :ios, '11.3'

target 'USBankTestProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for USBankTestProject

  target 'USBankTestProjectTests' do
    inherit! :search_paths
    # Pods for testing
    platform :ios, '11.3'
    pod 'Alamofire', '~> 4.0'

  end

  target 'USBankTestProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
